version: "3.9"
services:
  p1:
    build: .
    ports:
      - "8081:8080"
    privileged: true
    environment:
      - PROCESS_NUM=1
  p2:
    build: .
    ports:
      - "8082:8080"
    privileged: true
    environment:
      - PROCESS_NUM=2
  p3:
    build: .
    ports:
      - "8083:8080"
    privileged: true
    environment:
      - PROCESS_NUM=3
  p4:
    build: .
    ports:
      - "8084:8080"
    privileged: true
    environment:
      - PROCESS_NUM=4